---
- name: include variable overrides
  set_fact:
    _avideo_packages: "{{ avideo_packages | default(avideo_packages_default | sorted_get(overrides)) }}"
  vars:
    overrides:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
      - "{{ ansible_distribution | lower }}"
      - "{{ ansible_os_family | lower }}"
      - "default"
  tags:
    - always

- name: install avideo packages
  package:
    name: "{{ _avideo_packages }}"

- name: deploy avideo
  git:
    repo: "{{ avideo_main_project }}"
    dest: "{{ avideo_main_path  }}"
    version: "{{ avideo_main_release }}"
    force: yes

- name: deploy avideo encoder
  git:
    repo: "{{ avideo_encoder_project }}"
    dest: "{{ avideo_encoder_path }}"
    version: "{{ avideo_encoder_release }}"
    force: yes

- name: manage video folder
  file:
    dest: "{{ avideo_main_path }}/videos"
    state: directory
    group: "{{ avideo_user }}"
    owner: "{{ avideo_group }}"
    mode: 0755

- name: set permissions for avideo main
  file:
    dest: "{{ avideo_main_path }}"
    state: directory
    group: "{{ avideo_user }}"
    owner: "{{ avideo_group }}"
    recurse: yes

- name: flush handlers
  meta: flush_handlers

- block:

    - name: gather streamer configuration status
      stat:
        path: "{{ avideo_main_path }}/videos/configuration.php"
      register: avideo_config_stat

    - name: initialize streamer configuration
      uri:
        url: "{{ __avideo_url }}/install/checkConfiguration.php"
        method: POST
        body_format: form-urlencoded
        body:
          webSiteRootURL: "{{ __avideo_streamer_url_normalized }}"
          systemRootPath: "{{ __avideo_streamer_root_normalized }}"
          webSiteTitle: "{{ avideo_site_title }}"
          databaseHost: "{{ avideo_db_host }}"
          databasePort: "{{ avideo_db_port }}"
          databaseName: "{{ avideo_db_name }}"
          databaseUser: "{{ avideo_db_user }}"
          databasePass: "{{ avideo_db_pass }}"
          mainLanguage: "{{ avideo_language }}"
          systemAdminPass: "{{ avideo_admin_pass }}"
          contactEmail: "{{ avideo_contact_email }}"
          createTables: 1
      when: not avideo_config_stat.stat.exists
      no_log: "{{ not (avideo_debug | bool) }}"

    - name: gather streamer configuration status
      stat:
        path: "{{ avideo_main_path }}/videos/configuration.php"
      register: avideo_config_stat

    - name: verify streamer configuration status
      fail:
        msg: "{{ avideo_main_path }}/videos/configuration.php not found"
      when: not avideo_config_stat.stat.exists

    - name: remove install directory
      file:
        dest: "{{ avideo_main_path }}/install"
        state: absent
      when: avideo_config_stat.stat.exists
      changed_when: false

    - name: manage streamer configuration
      lineinfile:
        path: "{{ avideo_main_path }}/videos/configuration.php"
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
        backrefs: "{{ item.backrefs | default(omit) }}"
      loop_control:
        label: "{{ item.label }}"
      loop:
        - label: webSiteRootUrl
          regex: '^(\s*)\$global\[''webSiteRootUrl''\](\s*)=.*$'
          line: '\1$global[''webSiteRootUrl''] = ''{{ __avideo_streamer_url_normalized }}'';'
          backrefs: true
        - label: systemRootPath
          regex: '^\$global\[''systemRootPath''\](\s*)='
          line: '$global[''systemRootPath''] = ''{{ __avideo_streamer_root_normalized }}'';'
          backrefs: true
        - label: webSiteRootPath
          regex: '^\$global\[''webSiteRootPath''\](\s*)='
          line: '$global[''webSiteRootPath''] = ''{{ __avideo_streamer_url_path_normalized }}'';'
          backrefs: true
        - label: mysqlHost
          regex: '^\$mysqlHost(\s*)='
          line: '$mysqlHost = ''{{ avideo_db_host }}'';'
          backrefs: true
        - label: mysqlPort
          regex: '^\$mysqlPort(\s*)='
          line: '$mysqlPort = ''{{ avideo_db_port }}'';'
          backrefs: true
        - label: mysqlUser
          regex: '^\$mysqlUser(\s*)='
          line: '$mysqlUser = ''{{ avideo_db_user }}'';'
          backrefs: true
        - label: mysqlPass
          regex: '^\$mysqlPass(\s*)='
          line: '$mysqlPass = ''{{ avideo_db_pass }}'';'
          backrefs: true
        - label: mysqlDatabase
          regex: '^\$mysqlDatabase(\s*)='
          line: '$mysqlDatabase = ''{{ avideo_db_name }}'';'
          backrefs: true
      no_log: "{{ not (avideo_debug | bool) }}"

  when: avideo_config_manage | bool
  tags:
    - configure
    - streamer

- block:

    - name: gather encoder configuration status
      stat:
        path: "{{ avideo_encoder_path }}/videos/configuration.php"
      register: avideo_config_stat

    - block:

        - name: create configuration directory
          file:
            path: "{{ avideo_encoder_path }}/videos/"
            state: directory
            owner: www-data
            group: www-data

        - name: mysql query encoder configuration
          mysql_query:
            login_db: "{{ avideo_encoder_db_name }}"
            query: SELECT * FROM configurations
          register: encoder_data
          ignore_errors: true

        - name: remove record configurations_encoder
          mysql_query:
            login_db: "{{ avideo_encoder_db_name }}"
            query: DELETE FROM configurations WHERE id=1
          when:
            - ( encoder_data.rowcount | default(0) != 0 )
            - ( encoder_data.failed == false )

        - name: initialize encoder configuration
          uri:
            url: "{{ __avideo_url }}/upload/install/checkConfiguration.php"
            method: POST
            body_format: form-urlencoded
            body:
              webSiteRootURL: "{{ __avideo_encoder_url_normalized }}"
              systemRootPath: "{{ __avideo_encoder_root_normalized }}"
              databaseHost: "{{ avideo_db_host }}"
              databaseName: "{{ avideo_encoder_db_name }}"
              databaseUser: "{{ avideo_encoder_db_user }}"
              databasePass: "{{ avideo_encoder_db_pass }}"
              createTables: 1
              defaultPriority: 1
              allowedStreamers: "{{ __avideo_streamer_url_normalized }}"
              siteURL: "{{ __avideo_streamer_url_normalized }}"
              inputUser: "{{ avideo_admin_user }}"
              inputPassword: "{{ avideo_admin_pass }}"
          no_log: "{{ not (avideo_debug | bool) }}"

        - name: configure encoderURL into streamer site
          mysql_query:
            login_db: "{{ avideo_db_name }}"
            query: "UPDATE configurations SET encoderURL = '{{ __avideo_encoder_url_normalized }}' WHERE id=1"

      when: not avideo_config_stat.stat.exists

    - name: gather encoder configuration status
      stat:
        path: "{{ avideo_encoder_path }}/videos/configuration.php"
      register: avideo_config_stat

    - name: verify encoder configuration status
      fail:
        msg: "{{ avideo_encoder_path }}/videos/configuration.php not found"
      when: not avideo_config_stat.stat.exists

    - name: remove install directory
      file:
        dest: "{{ avideo_encoder_path }}/install"
        state: absent
      when: avideo_config_stat.stat.exists
      changed_when: false

    - name: manage encoder configuration
      lineinfile:
        path: "{{ avideo_encoder_path }}/videos/configuration.php"
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
        backrefs: "{{ item.backrefs | default(omit) }}"
      loop_control:
        label: "{{ item.label }}"
      loop:
        - label: webSiteRootUrl
          regex: '^(\s*)\$global\[''webSiteRootUrl''\](\s*)=.*$'
          line: '\1$global[''webSiteRootUrl''] = ''{{ __avideo_encoder_url_normalized }}'';'
          backrefs: true
        - label: systemRootPath
          regex: '^\$global\[''systemRootPath''\](\s*)='
          line: '$global[''systemRootPath''] = ''{{ __avideo_encoder_root_normalized }}'';'
          backrefs: true
        - label: webSiteRootPath
          regex: '^\$global\[''webSiteRootPath''\](\s*)='
          line: '$global[''webSiteRootPath''] = ''{{ __avideo_encoder_url_path_normalized }}'';'
          backrefs: true
        - label: mysqlHost
          regex: '^\$mysqlHost(\s*)='
          line: '$mysqlHost = ''{{ avideo_db_host }}'';'
          backrefs: true
        - label: mysqlPort
          regex: '^\$mysqlPort(\s*)='
          line: '$mysqlPort = ''{{ avideo_db_port }}'';'
          backrefs: true
        - label: mysqlUser
          regex: '^\$mysqlUser(\s*)='
          line: '$mysqlUser = ''{{ avideo_encoder_db_user }}'';'
          backrefs: true
        - label: mysqlPass
          regex: '^\$mysqlPass(\s*)='
          line: '$mysqlPass = ''{{ avideo_encoder_db_pass }}'';'
          backrefs: true
        - label: mysqlDatabase
          regex: '^\$mysqlDatabase(\s*)='
          line: '$mysqlDatabase = ''{{ avideo_encoder_db_name }}'';'
          backrefs: true
      no_log: "{{ not (avideo_debug | bool) }}"

  when: avideo_config_manage | bool
  tags:
    - configure
    - encoder

- block:

    - name: install dependecies
      apt:
        name: unzip

    - name: login to https://youphp.tube/marketplace/
      uri:
        url: https://youphp.tube/marketplace/objects/loginAVideo.json.php
        method: POST
        body_format: form-urlencoded
        body:
          user: "{{ avideo_plugin_store_user }}"
          pass: "{{ avideo_plugin_store_password }}"
      register: _login_youphp_tube

    - name: download avideo plugin
      get_url:
        url: "{{ item.url }}"
        dest: "{{ __avideo_plugin_path }}/{{ item.name }}.zip"
        timeout: 300
        headers:
          Cookie: "{{ _login_youphp_tube.set_cookie }}"
      loop: "{{ avideo_plugin }}"

    - name: uncompress plugin archives
      unarchive:
        src: "{{ __avideo_plugin_path }}/{{ item.name }}.zip"
        dest: "{{ __avideo_plugin_path }}"
        remote_src: yes
      loop: "{{ avideo_plugin }}"

    - name: manage video folder
      file:
        dest: "{{ __avideo_plugin_path }}/{{ item.name }}"
        state: directory
        group: "{{ avideo_user }}"
        owner: "{{ avideo_group }}"
        mode: 0755
      loop: "{{ avideo_plugin }}"

  when: avideo_manage_plugin | bool
  tags:
    - configure
    # - plugin

- block:

    - name: login to avideo
      uri:
        url: "{{ __avideo_url }}/objects/login.json.php"
        method: POST
        body_format: form-urlencoded
        body:
          user: "{{ avideo_admin_user }}"
          pass: "{{ avideo_admin_pass }}"
          redirectUri: "{{ __avideo_url }}"
      register: _login_avideo

    - name: query all plugins available
      uri:
        url: "{{ __avideo_url }}/objects/pluginsAvailable.json.php"
        method: POST
        body_format: json
        headers:
          Cookie: "{{ _login_avideo.cookies_string }}"
      register: _avideo_plugin_available

    - name: extract data plugin
      vars:
        _avideo_list_plugin: "{{ avideo_plugin | map(attribute='name') | list }}"
      set_fact:
        _avideo_to_change: "{{ _avideo_to_change | default([]) + [item] }}"
      loop: "{{ _avideo_plugin_available.json.rows }}"
      when: item.name in _avideo_list_plugin
      no_log: true

    - name: enable/disable plugins
      vars:
        _avideo_plugin_uuid: "{{ _avideo_to_change | selectattr('name','eq',item.name) }}"
        _enabled: "{{ _avideo_plugin_uuid | map(attribute='enabled') }}"
      uri:
        url: "{{ __avideo_url }}/objects/pluginSwitch.json.php"
        method: POST
        body_format: form-urlencoded
        headers:
          Cookie: "{{ _login_avideo.cookies_string }}"
        body:
          uuid: "{{ _avideo_plugin_uuid | map(attribute='uuid') }}"
          name: "{{ _avideo_plugin_uuid | map(attribute='name') }}"
          dir: "{{ _avideo_plugin_uuid | map(attribute='dir') }}"
          enable: "{{ item.state | default('true') }}"
      loop: "{{ avideo_plugin }}"
      when: _enabled == 'false'

    - name: plugin configuration
      vars:
        _avideo_plugin_uuid: "{{ _avideo_to_change | selectattr('name','eq',item.name) }}"
      uri:
        url: "{{ __avideo_url }}/objects/pluginAddDataObject.json.php"
        method: POST
        body_format: form-urlencoded
        headers:
          Cookie: "{{ _login_avideo.cookies_string }}"
        body:
          id: "{{ _avideo_plugin_uuid | map(attribute='id') }}"
          object_data: "{{ item.config }}"
      loop: "{{ avideo_plugin }}"
      when: item.config is defined

  when: avideo_manage_plugin | bool
  tags:
    - configure
    - plugin

- block:

    - name: manage backup script
      template:
        src: templates/backup.sh.j2
        dest: "{{ avideo_backup_bin }}"
        group: root
        owner: root
        mode: 0750
      vars:
        backup_path: "{{ avideo_backup_path }}"
        backup_source: "{{ avideo_main_path }}"
        backup_db_enable: "{{ avideo_backup_db_enable }}"
        backup_db_name: "{{ avideo_db_name }} {{ avideo_encoder_db_name }}"
        backup_identifier: "{{ avideo_backup_identifier }}"
        retention_period: "{{ avideo_backup_retention_days }}"

    - name: manage restore script
      template:
        src: templates/restore.sh.j2
        dest: "{{ avideo_restore_bin }}"
        group: root
        owner: root
        mode: 0750
      vars:
        backup_path: "{{ avideo_backup_path }}"
        backup_source: "{{ avideo_main_path }}"
        backup_identifier: "{{ avideo_backup_identifier }}"
        retention_period: "{{ avideo_backup_retention_days }}"
        app_daemon: "{{ apache_daemon }}"

    - name: manage backup cronjob
      cron:
        state: "{{ avideo_backup_cronjob_state }}"
        name: avideo-backup
        job: "{{ avideo_backup_bin }}"
        special_time: "{{ avideo_backup_cronjob_schedule }}"

    - name: create avideo backup motd pointers
      copy:
        dest: /etc/update-motd.d/99-avideo
        content: |
          #!/usr/bin/env bash
          echo
          echo run {{ avideo_backup_bin | basename }} to manually force snipeit backup creation
          echo run {{ avideo_restore_bin | basename }} to manually restore latest snipeit backup
          echo
        mode: 0755

  when: avideo_backup_manage | bool
  tags:
    - backup
